### PR TITLE
Update Byte Buddy to 1.12.6 (fixes #7)

### LINKED ISSUE #7: Byte Buddy version update
Continuing the investigation.

```
Caused by: java.lang.NegativeArraySizeException: -1
	at tech.httptoolkit.relocated.net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader.invoker(SourceFile:34)
	at tech.httptoolkit.relocated.net.bytebuddy.utility.dispatcher.JavaDispatcher$Invoker$CreationAction.run(SourceFile:1)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at tech.httptoolkit.relocated.net.bytebuddy.utility.dispatcher.JavaDispatcher.<clinit>(SourceFile:12)
```
This exception starts from version [1.11.6](https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.11.6). By looking at the generated source mapping I see that the attempt to create array with negative size is at this line:
https://github.com/raphw/byte-buddy/blob/c51396ba504c0a7397d912f8e621d060bc360483/byte-buddy-dep/src/main/java/net/bytebuddy/utility/dispatcher/JavaDispatcher.java#L1270

Which fails as in the byte code `Invoker` interface was replaced with concrete class (in this commit it's `Unsafe` which is a class and has hashCode which has zero arguments... so my **guess** it's that it fails on this.

-- fast forward to latest byte buddy

Return value of JavaDispatcher.invoker() is [`net.bytebuddy.utility.Invoker`](https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/main/java/net/bytebuddy/utility/Invoker.java) interface but in the byte code (after r8) it is substituted with [`DirectInvoker` ](https://github.com/raphw/byte-buddy/blob/cbcee69074d6401ce4a2bd193d42fe64c8bec51a/byte-buddy-dep/src/main/java/net/bytebuddy/utility/dispatcher/JavaDispatcher.java#L455) class which again has one method with 0 arguments.

The exception is thrown at this line:
https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/main/java/net/bytebuddy/utility/dispatcher/JavaDispatcher.java#L1287

This can be fixed by leaving the `Invoker` interface untouched by adding
```
-keep class tech.httptoolkit.relocated.net.bytebuddy.utility.Invoker { *; }
```
to `r8-rules.txt`. This way the interface is not replaced and byte buddy is able to create DynamicClassloader.

Afterwards the agent is able to attach to processes like  before and we reach the second (or actually it is the first issue). 

Since version [1.11.3](https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.11.3) we are greeted by multiple SSLHandshakeExceptions during tests:
```
Unexpected failure for new http-url-conn: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```
I currently have no idea what caused this... yet... 

---

Looking at the standalone test the exception is also there (but it manages to succeed?)
https://github.com/httptoolkit/jvm-http-proxy-agent/runs/4601280285?check_suite_focus=true

### PR DESCRIPTION
**Pull request by kamko**
all info in #7

### CODE REVIEW

**Comment by pimterry** [comment]
Just to update here - I am still looking into this, but I haven't fixed it yet.

The interesting bit is that `-keep class tech.httptoolkit.relocated.** { *; }` isn't sufficient. That means there's some low-level detail of the transformation that r8 is doing that breaks something. That's not super surprising (I can imagine all sorts  of changes which shouldn't affect any normal usage but do affect bytebuddy somehow) but it's quite inconvenient.

We can work around this by editing the include/exclude rules in the `distJar` gradle task (which copies in specific original untouched class files on top of the r8 output) and that works, but it's a tradeoff to try and do that for the smallest compatible set of files required to make this work.

I do have a working patch, by excluding `net.bytebuddy.**` and `org.objectweb.asm.**` entirely from r8, and adding an include/exclude for just `tech/httptoolkit/relocated/net/bytebuddy/agent/**/*` to the gradle `distJar` build. That leaves us with a dist jar of 3MB though, which is a fair jump on the 1.75MB JARs we've had until now. This compares to 4.6MB for the unminified build. I'm also not 100% sure why this works yet, which i don't love.

At the end of the day, it's not a disaster to push the size up, and maybe we'll have to, but that extra weight goes directly onto the HTTP Toolkit download for every user, so I'd like to limit it if I can, or at least explain exactly what's going on and why shrinking this is impossible.

I'll keep digging and update when I have more :smiley:. Let me know if you work out any clues on your end in the meantime!

**Comment by kamko** [comment]
Unfortunately didn't have time to look into this.

It's really weird that keeping all shaded classes is not enough for this to work. 
Did you also try to exclude only ASM or only bytebuddy?

I think that increasing the JAR size by 1.25MB (I know that it's 70% 😄) hurts but the installer is at 80MB already (at least for win). If we still try to minimize the bytebuddy/asm code these kind of problems could bite us again in the future. Although I understand the struggle as not everyone is using this and would be penalized by having to download more...

**Comment by pimterry** [comment]
> I think that increasing the JAR size by 1.25MB (I know that it's 70% :smile:) hurts but the installer is at 80MB already (at least for win).

True, but these kind of things add up. And this also affects server updates (currently ~30MB) and this JAR gets copied into Docker containers when they're intercepted too (as part of a payload of about 10MB total). It's not critical, but I would like to avoid letting any of this creep up too much.

Anyway, I've managed to pull the size down a bit further (to 2.3MB) and simplify the config en route by disabling R8's automated optimizations entirely. Looks like those were only saving 0.1MB anyway, and hopefully that'll make this much less fragile in future generally, since it now mutates the code far less. I've pushed that change here.

I think this'll do for now. I'm going to merge this and release as 1.3.0 in just a sec. I've also fixed the annoying R8 build warnings from Akka & Scala on `main`, so hopefully it'll be easier to investigate and debug all any similar issues like this in future.

Thanks again for all your help and hard work on this! Really glad we've managed to get it working :smile:

**Comment by kamko** [comment]
Great!, good job :)

**Pull request merged**
